name: thesis
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pytorch=2.4
  - torchvision
  - pytorch-cuda=11.8
  - supervision
  - pip
  - pip:
      - openai
      - langchain
      - pdfplumber
      - pypdf2
      - faiss-cpu
      - pandas
      - scikit-image
      - einops
      - timm
      - rich
      - hydra-core
      - hydra-submitit-launcher
      - hydra-colorlog
      - pyrootutils
      - pycocotools
      - fvcore
      - iopath
      - "git+https://github.com/facebookresearch/detectron2"
      - "git+https://github.com/facebookresearch/pytorch3d.git@V0.7.8"
