scene_name: ???
output_dir: /scratch/izar/cizinsky/thesis/output/${scene_name}

frame_extraction:
  video_path: /home/cizinsky/soccer_net/clips/modric_vs_ribberi.mp4
  sample_fps: 24

hydra:
  run:
    dir: /scratch/izar/cizinsky/thesis/hydra/${now:%Y-%m-%d}_${now:%H-%M-%S}
  job:
    chdir: False