project: master-thesis
entity: ludekcizinsky
internal_run_id: "pretty-field-33_k0fthj1m" # this is for resuming

# --- Hydra settings
hydra:
  run:
    dir: /scratch/izar/cizinsky/thesis/hydra/${now:%Y-%m-%d}_${now:%H-%M-%S}
  job:
    chdir: False