scene_name: football_high_res
group_name: v1_default

# --- Input / output paths
output_dir: /scratch/izar/cizinsky/thesis/output/${scene_name}
preprocess_dir: /scratch/izar/cizinsky/multiply-output/preprocessing/data/${scene_name}

# --- Rendering options
render_bg: true
render_tids: [0, 1]

# --- Rendering settings
device: cuda
sh_degree: 3
cloud_downsample: 10
lbs_knn: 30
video_fps: 12

# --- Hydra settings
hydra:
  run:
    dir: /scratch/izar/cizinsky/thesis/hydra/${now:%Y-%m-%d}_${now:%H-%M-%S}
  job:
    chdir: False
